services:
  # configures all the services with config files in volumes
  setup:
    hostname: setup.backend.saas.local
    image: registry.choria.io/choria/choria:latest
    entrypoint: /setup/setup.sh
    user: root
    volumes:
      - ./setup/:/setup
      - issuer:/configuration/issuer
      - provisioner:/configuration/provisioner
      - broker:/configuration/broker
      - customer-tools:/configuration/customer/tools
      - customer-app1:/configuration/customer/app1
      - customer-app2:/configuration/customer/app2
      - customer-app3:/configuration/customer/app3
      - saas-nats:/configuration/saas-nats
      - redpanda:/configuration/redpanda

  shell:
    hostname: shell.backend.saas.local
    image: registry.choria.io/choria/choria:latest
    user: root
    working_dir: /machine-room
    entrypoint: /bin/bash
    tty: true
    environment:
      - NATS_URL=saas-nats.backend.saas.local
    volumes:
      - issuer:/machine-room/issuer
      - provisioner:/machine-room/provisioner
      - broker:/machine-room/broker
      - customer-tools:/machine-room/customer/tools
      - customer-app1:/machine-room/customer/app1
      - customer-app2:/machine-room/customer/app2
      - customer-app3:/machine-room/customer/app3
      - saas-nats:/machine-room/nats
      - redpanda:/machine-room/redpanda


  # serves up autonomous agents over http
  plugins:
    hostname: plugins.backend.saas.local
    image: httpd:latest
    dns_search: backend.saas.local
    volumes:
      - ./setup/agents:/usr/local/apache2/htdocs/
    depends_on:
      setup:
        condition: service_completed_successfully

  # NATS JetStream server that represents the SaaS Backend
  saas-nats:
    hostname: saas-nats.backend.saas.local
    image: synadia/nats-server:nightly
    dns_search: backend.saas.local
    command: --config /machine-room/server.conf
    environment:
      NATS_USER: backend
      NATS_PASSWORD: s3cret
    volumes:
      - saas-nats:/machine-room
    depends_on:
      setup:
        condition: service_completed_successfully

  # Configures a few streams once the SaaS JetStream is up
  saas-stream-setup:
    image: synadia/nats-server:nightly
    dns_search: backend.saas.local
    entrypoint: /machine-room/create.sh
    volumes:
      - saas-nats:/machine-room
    depends_on:
      saas-nats:
        condition: service_started

  # MongoDB to host node database and other state
  mongo:
    image: mongo
    hostname: mongo.backend.saas.local
    dns_search: backend.saas.local
    restart: always
    command: --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: mr
      MONGO_INITDB_ROOT_PASSWORD: s3cret
      MONGO_INITDB_DATABASE: machineroom
    depends_on:
      setup:
        condition: service_completed_successfully

  redpanda-connect-nodes:
    image: docker.redpanda.com/redpandadata/connect
    hostname: redpanda-connect.backend.saas.local
    dns_search: backend.saas.local
    volumes:
      - redpanda:/etc/redpanda
    command: run /etc/redpanda/nodes.yaml
    depends_on:
      saas-stream-setup:
        condition: service_completed_successfully

  dashboard:
    hostname: dashboard.managed.example.net
    user: root
    depends_on:
      mongo:
        condition: service_started
    environment:
      MONGO_URI: mongodb://mr:s3cret@mongo:27017
    ports:
      - 8080:8080
    build:
      context: dashboard
      dockerfile: Dockerfile

  # choria broker where provisioning happens
  provision-borker:
    hostname: provision-broker.backend.saas.local
    image: registry.choria.io/choria/choria:latest
    dns_search: backend.saas.local
    command: broker run --config /etc/choria/broker.conf
    volumes:
      - broker:/etc/choria
    depends_on:
      saas-stream-setup:
        condition: service_completed_successfully

  # choria provisioner used to onboard customers
  provisioner:
    hostname: provisioner.backend.saas.local
    image: registry.choria.io/choria/provisioner:latest
    dns_search: backend.saas.local
    command: --config /etc/choria-provisioner/provisioner.yaml --choria-config /etc/choria-provisioner/choria.cfg
    volumes:
      - provisioner:/etc/choria-provisioner
    depends_on:
      provision-borker:
        condition: service_started

  # A customer running our example agent
  customer-tools:
    hostname: tools.managed.example.net
    user: root
    depends_on:
      provision-borker:
        condition: service_started
    volumes:
      - customer-tools:/etc/saas-manager/
    build:
      context: agent
      dockerfile: Dockerfile

  customer-app1:
    hostname: app1.managed.example.net
    user: root
    depends_on:
      provision-borker:
        condition: service_started
    volumes:
      - customer-app1:/etc/saas-manager/
    build:
      context: agent
      dockerfile: Dockerfile

  customer-app2:
    hostname: app2.managed.example.net
    user: root
    depends_on:
      provision-borker:
        condition: service_started
    volumes:
      - customer-app2:/etc/saas-manager/
    build:
      context: agent
      dockerfile: Dockerfile

  customer-app3:
    hostname: app3.managed.example.net
    user: root
    depends_on:
      provision-borker:
        condition: service_started
    volumes:
      - customer-app3:/etc/saas-manager/
    build:
      context: agent
      dockerfile: Dockerfile

volumes:
  issuer:
  provisioner:
  broker:
  customer-tools:
  customer-app1:
  customer-app2:
  customer-app3:
  saas-nats:
  redpanda: